services:
  database:
    container_name: cit-database
    image: mysql:latest
    restart: always
    env_file:
      - ./database.dev.env
    ports:
      - "3306:3306"
    networks:
      - backend
      - database
  backend:
    container_name: cit-back
    build:
      context: ./src/back
      dockerfile: Dockerfile.dev
    volumes:
      - ./src/back/src:/app/src
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://database:3306/cit
      SPRING_DATASOURCE_USERNAME: dev
      SPRING_DATASOURCE_PASSWORD: dev
      SPRING_LOG_LEVEL: DEBUG
    ports:
      - "8080:8080"
      - "8081:8081"
    depends_on:
      - database
    networks:
      - backend
      - frontend
  frontend:
    container_name: cit-front
    build:
      context: ./src/front
      dockerfile: Dockerfile.dev
    ports:
      - "3000:3000"
    volumes:
      - ./src/front/src:/app/src
      - ./src/front/public:/app/public
      - ./src/front/tailwind.config.js:/app/tailwind.config.js
    depends_on:
      - backend
    networks:
      - frontend
    environment:
      - WATCHPACK_POLLING=true
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: cit-phpmyadmin
    restart: always
    depends_on:
      - database
    environment:
      PMA_HOST: database
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3001:80"
    networks:
      - database
networks:
  backend:
  database:
  frontend:
  phpmyadmin:
