services:
  database:
    container_name: cit-database
    image: mysql:latest
    environment:
      MYSQL_DATABASE: cit
      MYSQL_ALLOW_EMPTY_PASSWORD: true
    networks:
      - backend
  backend:
    container_name: cit-back
    build: ./src/back
    volumes:
      - ./src/back/.m2:/app/.m2
      - ./src/back/.mvn:/app/.mvn
      - ./src/back/src:/app/src
    ports:
      - "8080:8080"
      - "8081:8081"
    depends_on:
      - database
    networks:
      - backend
      - frontend
  frontend:
    container_name: cit-front
    build: ./src/front
    ports:
      - "3000:3000"
    volumes:
      - ./src/front/src:/app/src
      - ./src/front/public:/app/public
      - ./src/front/tailwind.config.js:/app/tailwind.config.js
    depends_on:
      - backend
    networks:
      - frontend
    environment:
      - WATCHPACK_POLLING=trues
networks:
    backend:
        driver: bridge
    frontend:
        driver: bridge
