version: "3.8"
services:
  database:
    container_name: cit-database
    image: mysql:latest
    restart: always
    environment:
      MYSQL_DATABASE: cit
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: dev
      MYSQL_PASSWORD: dev
    networks:
      - backend
      - database
  backend:
    container_name: cit-back
    build: ./src/back
    volumes:
      - ./src/back/.m2:/app/.m2
      - ./src/back/.mvn:/app/.mvn
      - ./src/back/src:/app/src
    ports:
      - "8080:8080"
      - "8081:8081"
    depends_on:
      - database
    networks:
      - backend
      - frontend
  frontend:
    container_name: cit-front
    build: ./src/front
    ports:
      - "3000:3000"
    volumes:
      - ./src/front/src:/app/src
      - ./src/front/public:/app/public
      - ./src/front/tailwind.config.js:/app/tailwind.config.js
    depends_on:
      - backend
    networks:
      - frontend
    environment:
      - WATCHPACK_POLLING=trues
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: cit-phpmyadmin
    restart: always
    depends_on:
      - database
    environment:
      PMA_HOST: cit-database
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3001:80"
    networks:
      - database
networks:
  backend:
    driver: bridge
  frontend:
    driver: bridge
  database:
    driver: bridge
