FROM node:22 AS builder

ENV HOME=/app

WORKDIR $HOME

COPY package*.json ./
RUN npm i

COPY public/ ./public
COPY src/ ./src
COPY tailwind.config.js ./
RUN npm run build

FROM nginx:stable-alpine

COPY --from=builder /app/build /usr/share/nginx/html